name: deployment
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy application
              run: echo "Deploying application..."
            # - name: Get Code
            #   run: |
            #     echo "Fetching code from repository..."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Get Code
              uses: actions/checkout@v6
            - name: Install Node 20
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: Run check
              run: node -v
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Build Project
              run: npm run build
            - name: Deploy Project
              run: echo "Deploying project..."